// Vitest Snapshot v1, https://vitest.dev/guide/snapshot.html

exports[`showError > should generate an error report matching snapshot 1`] = `
"
This is an automated error report generated by the application.

- **Error:** Error
- **Message:** Test error
- **Stack Trace:**
\`\`\`text
Error: Test error
    at testFunction (test.js:1:1)
\`\`\`
---
[Please describe what you were doing when the error occurred here.]


Please Upload the logs from the following location:
test.log

---
log1
log2
---

"
`;

exports[`showError > should generate an error report matching snapshot 2`] = `
"An unexpected error occurred. Please try the following:

- Restart the application.
- Check your internet connection.
- Raise an issue if the problem persists.

An error report has been prepared for you and opened in the browser to share with the developers, should you choose to do so.
"
`;
